stack:
    build: ./stack
    dockerfile: Dockerfile
    ports:
        - "80:80"
    #restart: always
    volumes:
        - /home/aguinelo/workspace/f/:/www
        - ./stack/php.ini:/usr/local/etc/php/php.ini
        - ./hosts.conf:/etc/nginx/conf.d/default.conf
    # links:
    #     - mysql
